<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE9dzG3Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE9dzG3Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE9dzG3Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE9dzG3Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE9dzG3Q\App_KernelDevDebugContainer([
    'container.build_hash' => 'E9dzG3Q',
    'container.build_id' => 'afb52686',
    'container.build_time' => 1687203382,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE9dzG3Q');
