<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9CbdHOS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9CbdHOS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9CbdHOS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9CbdHOS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9CbdHOS\App_KernelDevDebugContainer([
    'container.build_hash' => '9CbdHOS',
    'container.build_id' => '2ba2b755',
    'container.build_time' => 1687978310,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9CbdHOS');
